"""Single-window Qt front end: video on the right, sectioned controls on the left.

Why this exists next to `steam-tune`: HighGUI has no section headers, so that tuner
spreads its knobs over four windows you drag apart by hand, and it has no file dialog
and nowhere to put the generic image controls. Qt has all of it, and a real thread --
decoding never blocks the widgets.

Nothing here is duplicated. `Config` and the whole plume pipeline come from `plume`,
the frame cache is `tune.Clip`, and the Steam-Tune sliders are generated by looping
over `tune.KNOBS` -- the same table that builds the HighGUI trackbars. One knob table,
one cache, two front ends.

Transport is the same as `steam-tune`: space plays and pauses, `.` and `,` step, and
the seek bar under the video jumps anywhere in the clip. Seeking is why the worker
uses `Clip` rather than reading the file straight through -- `Clip` caches raw frames
and per-frame temporal statistics, so stepping around re-uses the neighbours the
previous frame already decoded and aligned.

Processing order, one chain per displayed frame:

    frame from Clip (already cropped and scaled)
        -> contours (optional)  ------------> the region the plume pipeline may use
        -> plume pipeline (optional), its masks cut down to that region
        -> brightness / contrast / saturation / gamma
        -> plume outlines, then contour outlines
        -> background subtraction (optional)
        -> colour space view

Contours and the plume pipeline both read the frame before the adjustment sliders
touch it: every threshold in the plume pipeline is a percentile of the temperature
index, and a gamma or contrast change would move the exact percentiles a calibration
was tuned against. The adjustment sliders are for your eyes, not for the segmentation.

With the contour section on, the plume pipeline is confined to the pixels the contours
enclose -- everything outside is dropped from the masks, and a source that vents
outside the contours disappears from the count. The percentile thresholds are still
taken over the whole frame, for the same reason `plume_mask`'s own `roi` argument
takes them over the whole frame: a region that is mostly plume would push its own
p_hi through the roof and then find nothing.
"""

import json
import sys
from dataclasses import asdict, dataclass, fields
from functools import lru_cache
from pathlib import Path
from time import perf_counter

import cv2
import numpy as np
from PyQt6.QtCore import Qt, QThread, pyqtSignal
from PyQt6.QtGui import QImage, QKeySequence, QPixmap, QShortcut
from PyQt6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QFileDialog,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QMainWindow,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSlider,
    QToolBox,
    QVBoxLayout,
    QWidget,
)

from .plume import Config, annotate, build_config, plume_masks
from .tune import INT_FIELDS, KNOBS, PANELS, Clip

SPACES = ("Default (BGR)", "Grayscale", "HSV", "LAB")
STEAM_VIEWS = ("Frame", "Temperature", "Motion")
CONTOUR_VIEWS = ("Outlines", "Filled mask", "Hidden")
CONTOUR_COLOR = (0, 255, 255)  # BGR yellow: not one of plume.py's three overlay colours


@dataclass(frozen=True)
class Settings:
    """Everything the generic sections control, as one immutable bundle.

    Frozen on purpose: the GUI thread hands the worker a whole new object rather than
    mutating fields under it. Rebinding one attribute is atomic, so the worker always
    reads a self-consistent set of values and neither side needs a lock.
    """

    brightness: int = 0
    contrast: float = 1.0
    saturation: float = 1.0
    gamma: float = 1.0
    space: int = 0
    contours: bool = False
    contour_thresh: int = 0  # 0 picks the threshold with Otsu
    contour_min_area: int = 200
    contour_view: int = 0
    bgsub: bool = False
    bgsub_knn: bool = False
    bgsub_mask_only: bool = True
    steam: bool = False
    steam_view: int = 0
    scale: float = 1.0


@lru_cache(maxsize=64)
def _gamma_lut(gamma: float) -> np.ndarray:
    """256-entry gamma curve, cached -- rebuilding it every frame is pure waste."""
    return np.clip((np.arange(256) / 255.0) ** (1.0 / gamma) * 255, 0, 255).astype(np.uint8)


def adjust(bgr: np.ndarray, s: Settings) -> np.ndarray:
    """Brightness, contrast, saturation and gamma. Returns the input at the defaults.

    Each stage is skipped when its knob sits at identity, so an untouched panel costs
    nothing per frame. Nothing here writes in place: the frame belongs to Clip's cache
    and gets shown again on the next seek.
    """
    out = bgr
    if s.contrast != 1.0 or s.brightness:
        out = cv2.convertScaleAbs(out, alpha=s.contrast, beta=s.brightness)
    if s.saturation != 1.0:
        # split/merge rather than an in-place slice: hsv[:, :, 1] is a non-contiguous
        # view and OpenCV refuses those.
        h, sat, v = cv2.split(cv2.cvtColor(out, cv2.COLOR_BGR2HSV))
        out = cv2.cvtColor(
            cv2.merge((h, cv2.convertScaleAbs(sat, alpha=s.saturation), v)), cv2.COLOR_HSV2BGR
        )
    if s.gamma != 1.0:
        out = cv2.LUT(out, _gamma_lut(s.gamma))
    return out


def to_space(bgr: np.ndarray, space: int) -> np.ndarray:
    """The chosen colour space, always as a 3-channel image the label can show.

    HSV and LAB come out as false colour -- H plotted as blue is not meaningful, it is
    just what looking at the raw channels looks like, which is the point of the view.
    """
    if space == 1:
        return cv2.cvtColor(cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY), cv2.COLOR_GRAY2BGR)
    if space == 2:
        return cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    if space == 3:
        return cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    return bgr


def contours_of(bgr: np.ndarray, s: Settings) -> tuple[list, np.ndarray]:
    """Outlines of the bright regions, plus the filled 0/1 mask they enclose.

    Threshold on brightness rather than on an edge detector: the camera baked a
    colormap in, so on this footage "bright" means "hot", and the region worth handing
    to the plume pipeline is the hot one. A threshold of 0 hands the choice to Otsu,
    which is the right default on a clip whose exposure drifts under AGC.

    Only the outermost contours are kept -- a hot region with a cooler hole in it is
    still one region, and the hole should not carve itself out of the plume search.
    """
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    flags = cv2.THRESH_BINARY | (cv2.THRESH_OTSU if s.contour_thresh == 0 else 0)
    _, binary = cv2.threshold(gray, s.contour_thresh, 255, flags)
    found, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    keep = [c for c in found if cv2.contourArea(c) >= s.contour_min_area]
    inside = np.zeros(gray.shape, np.uint8)
    cv2.drawContours(inside, keep, -1, 1, cv2.FILLED)
    return keep, inside


def confine(found: list, inside: np.ndarray) -> list:
    """Plume masks with everything outside `inside` removed; empty ones dropped.

    Multiplication, not a bitwise and: the masks store 2 for core and `2 & 1` is 0,
    which would erase exactly the pixels that matter most.
    """
    cut = [(roi, box, mask * inside) for roi, box, mask in found]
    return [entry for entry in cut if entry[2].any()]


def to_qimage(bgr: np.ndarray) -> QImage:
    """BGR ndarray -> QImage that owns its pixels.

    The `.copy()` is not optional: QImage wraps the numpy buffer without taking a
    reference, so the array is freed the moment this function returns and the widget
    paints garbage.
    """
    rgb = np.ascontiguousarray(cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB))
    h, w, _ = rgb.shape
    return QImage(rgb.data, w, h, 3 * w, QImage.Format.Format_RGB888).copy()


class VideoWorker(QThread):
    """Renders whichever frame the transport points at, off the GUI thread.

    Owns the `Clip`; the GUI never touches it. Everything the GUI can change is a
    single attribute assignment -- `cfg`, `settings`, `idx`, `playing` -- which is
    atomic, so no lock is involved. The loop is driven by `idx`, not by the file
    position: playing is just "advance idx after each frame", which makes pause, step
    and seek the same code path.
    """

    frame_ready = pyqtSignal(QImage)
    status = pyqtSignal(str)
    opened = pyqtSignal(int)  # frame count, once the clip is readable
    position = pyqtSignal(int)  # current frame, so the seek bar follows playback

    def __init__(self, path: str, cfg: Config, settings: Settings):
        super().__init__()
        self.path = path
        self.cfg = cfg
        self.settings = settings
        self.idx = 0
        self.playing = True
        self._running = True
        self._sub = None
        self._sub_knn = None

    def stop(self) -> None:
        self._running = False
        self.wait()

    def seek(self, idx: int) -> None:
        self.idx = idx

    def step(self, frames: int) -> None:
        self.playing = False
        self.idx = max(0, self.idx + frames)

    def toggle(self) -> None:
        self.playing = not self.playing

    def reset_bgsub(self) -> None:
        """Throw the learned background away; the model re-seeds on the next frame."""
        self._sub = None

    def _background(self, frame: np.ndarray, s: Settings) -> np.ndarray:
        if self._sub is None or self._sub_knn != s.bgsub_knn:
            self._sub_knn = s.bgsub_knn
            self._sub = (
                cv2.createBackgroundSubtractorKNN()
                if s.bgsub_knn
                else cv2.createBackgroundSubtractorMOG2()
            )
        fg = self._sub.apply(frame)
        if s.bgsub_mask_only:
            return cv2.cvtColor(fg, cv2.COLOR_GRAY2BGR)
        # MOG2 marks shadows 127 and they survive the mask, which is what you want here:
        # a shadowed part of a moving object is still the moving object.
        return cv2.bitwise_and(frame, frame, mask=fg)

    def run(self) -> None:
        try:
            clip = Clip(self.path, self.settings.scale)
        except SystemExit as exc:  # Clip's way of saying the file is unreadable
            self.status.emit(str(exc))
            return
        scale = self.settings.scale
        fps = clip.cap.get(cv2.CAP_PROP_FPS)
        delay = max(1, int(1000 / fps)) if fps and fps > 1 else 33
        self.opened.emit(clip.count)

        last = None
        while self._running:
            cfg, s = self.cfg, self.settings  # one snapshot per frame, never re-read
            if s.scale != scale:
                # The cache holds frames at one scale, so a new scale is a new Clip.
                clip, scale = Clip(self.path, s.scale), s.scale
                self.opened.emit(clip.count)
            idx = self.idx = max(0, min(clip.count - 1, self.idx))

            # Paused on a frame nobody has re-tuned: there is nothing new to draw, and
            # redrawing anyway would spin a core for a still image.
            state = (idx, cfg, s)
            if state == last and not self.playing:
                self.msleep(30)
                continue
            last = state

            stats = None
            if s.steam:
                stats = clip.stats(idx, cfg)
                if stats is None:  # ran out of neighbours at the end of the clip
                    self.playing = False
                    self.idx = max(0, idx - cfg.stride)
                    continue
                raw = stats[0]
            else:
                got = clip.at(idx)
                if got is None:
                    self.playing = False
                    continue
                raw = got[0]

            note, frame = "", raw
            polys, inside = [], None
            if s.contours:
                polys, inside = contours_of(raw, s)
                note += f" contours={len(polys)}"

            found = []
            if stats is not None:
                _, temp, motion, bg = stats
                t0 = perf_counter()
                found = plume_masks(temp, motion, bg, cfg)
                if inside is not None:
                    found = confine(found, inside)
                ms = (perf_counter() - t0) * 1000
                if s.steam_view == 1:
                    frame = cv2.applyColorMap(temp, cv2.COLORMAP_INFERNO)
                elif s.steam_view == 2:
                    frame = cv2.applyColorMap(
                        np.clip(motion * 4, 0, 255).astype(np.uint8), cv2.COLORMAP_TURBO
                    )
                core = sum(int((m == 2).sum()) for *_, m in found)
                halo = sum(int((m == 1).sum()) for *_, m in found)
                note += f" src={len(found)} core={core} halo={halo} {ms:.0f}ms"

            work = adjust(frame, s)
            if s.contours and s.contour_view == 1:
                work = cv2.cvtColor(inside * 255, cv2.COLOR_GRAY2BGR)
            if found:
                work = annotate(work, found)  # after the sliders: overlays keep their colours
            if polys and s.contour_view == 0:
                work = work.copy()  # never draw into Clip's cached frame
                cv2.drawContours(work, polys, -1, CONTOUR_COLOR, 2)
            if s.bgsub:
                work = self._background(work, s)
            work = to_space(work, s.space)

            self.frame_ready.emit(to_qimage(work))
            self.position.emit(idx)
            self.status.emit(
                f"f{idx}/{clip.count - 1} {work.shape[1]}x{work.shape[0]}{note}"
                f" {'>' if self.playing else '||'}"
            )
            if self.playing:
                # With the plume pipeline on, a step is a *sampled* frame -- the frames
                # in between are the ones its neighbours are measured against.
                self.idx = idx + (cfg.stride if s.steam else 1)
                if self.idx > clip.count - 1:
                    self.idx, self.playing = clip.count - 1, False
            self.msleep(delay if not s.steam else 1)  # the plume pipeline paces itself


class Knob(QWidget):
    """Name, slider and live value in one row.

    Qt sliders are integers like HighGUI trackbars, so a knob that needs decimals is
    stored multiplied by `scale` and divided on the way out -- the same trick, and the
    same `scale` column, that `tune.KNOBS` already carries.
    """

    def __init__(self, name: str, lo: float, hi: float, value: float, scale: int = 1, tip: str = ""):
        super().__init__()
        self.scale = scale
        self.slider = QSlider(Qt.Orientation.Horizontal)
        self.slider.setRange(int(lo * scale), int(hi * scale))
        self.slider.setValue(int(round(value * scale)))
        self.readout = QLabel()
        self.readout.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)

        grid = QGridLayout(self)
        grid.setContentsMargins(0, 2, 0, 2)
        grid.addWidget(QLabel(name), 0, 0)
        grid.addWidget(self.readout, 0, 1)
        grid.addWidget(self.slider, 1, 0, 1, 2)
        if tip:
            self.setToolTip(tip)
        self.slider.valueChanged.connect(lambda _: self.readout.setText(f"{self.value():g}"))
        self.readout.setText(f"{self.value():g}")

    def value(self) -> float:
        return self.slider.value() / self.scale

    def set_value(self, value: float) -> None:
        self.slider.setValue(int(round(value * self.scale)))


class MainWindow(QMainWindow):
    def __init__(self, cfg: Config):
        super().__init__()
        self.setWindowTitle("steam-detector")
        self.cfg = cfg
        self.settings = Settings()
        self.worker: VideoWorker | None = None

        self.video = QLabel("open a video to start")
        self.video.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.video.setMinimumSize(640, 360)
        self.video.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)

        scroll = QScrollArea()
        scroll.setWidget(self._panel())
        scroll.setWidgetResizable(True)
        scroll.setFixedWidth(400)

        right = QWidget()
        column = QVBoxLayout(right)
        column.addWidget(self.video, 1)
        column.addWidget(self._transport())

        central = QWidget()
        layout = QHBoxLayout(central)
        layout.addWidget(scroll)
        layout.addWidget(right, 1)
        self.setCentralWidget(central)
        self.statusBar().showMessage("ready")

        # Same keys as steam-tune, so muscle memory carries over between the two.
        for keys, slot in (
            ("Space", self.toggle_play),
            (".", lambda: self.step(+1)),
            (",", lambda: self.step(-1)),
        ):
            QShortcut(QKeySequence(keys), self, slot)

    # --- video transport ---------------------------------------------------

    def _transport(self) -> QWidget:
        """Play/pause, step, and the seek bar -- under the video, where a player puts them."""
        self.b_play = self._button("Pause", self.toggle_play)
        self.seek = QSlider(Qt.Orientation.Horizontal)
        self.seek.setRange(0, 0)
        self.seek.setEnabled(False)
        self.seek.valueChanged.connect(self.on_seek)
        self.frame_label = QLabel("—")

        bar = QWidget()
        row = QHBoxLayout(bar)
        row.setContentsMargins(0, 0, 0, 0)
        row.addWidget(self._button("◀", lambda: self.step(-1)))
        row.addWidget(self.b_play)
        row.addWidget(self._button("▶", lambda: self.step(+1)))
        row.addWidget(self.seek, 1)
        row.addWidget(self.frame_label)
        return bar

    def toggle_play(self) -> None:
        if self.worker:
            self.worker.toggle()
            self.b_play.setText("Pause" if self.worker.playing else "Play")

    def step(self, direction: int) -> None:
        """One sampled frame, i.e. `stride` raw frames when the plume pipeline is on."""
        if self.worker:
            self.worker.step(direction * (self.cfg.stride if self.settings.steam else 1))
            self.b_play.setText("Play")

    def on_seek(self, value: int) -> None:
        if self.worker:
            self.worker.seek(value)

    def on_opened(self, count: int) -> None:
        self.seek.setEnabled(True)
        with_signals_off(self.seek, lambda: self.seek.setRange(0, max(0, count - 1)))

    def on_position(self, idx: int) -> None:
        # Signals off: the worker moved the frame, so writing it back as a user seek
        # would be a loop -- and would fight anyone dragging the handle.
        with_signals_off(self.seek, lambda: self.seek.setValue(idx))
        self.frame_label.setText(str(idx))

    # --- panel construction ------------------------------------------------

    def _panel(self) -> QWidget:
        """One QToolBox page per section. QToolBox collapses natively -- no custom widget.

        Load/Save sit under the toolbox rather than inside a page: one file holds every
        knob in the window, so burying the buttons in one section would misfile them.
        """
        box = QToolBox()
        box.addItem(self._source_page(), "Video Source")
        box.addItem(self._basic_page(), "Basic Adjustments")
        box.addItem(self._space_page(), "Color Spaces")
        box.addItem(self._contour_page(), "Contour Finding")
        box.addItem(self._motion_page(), "Motion / Background Subtraction")
        box.addItem(self._steam_page(), "Steam-Tune Controls")

        panel = QWidget()
        column = QVBoxLayout(panel)
        column.addWidget(box, 1)
        buttons = QHBoxLayout()
        buttons.addWidget(self._button("Load tune.json…", self.load_session))
        buttons.addWidget(self._button("Save tune.json…", self.save_session))
        column.addLayout(buttons)
        return panel

    def _page(self, *widgets) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        for widget in widgets:
            layout.addWidget(widget)
        layout.addStretch(1)
        return page

    def _button(self, text: str, slot) -> QPushButton:
        button = QPushButton(text)
        button.clicked.connect(slot)
        return button

    def _source_page(self) -> QWidget:
        self.k_scale = Knob("Processing scale", 0.25, 1.0, 1.0, 100, "work at this fraction of size")
        warn = QLabel(
            "Area knobs count pixels of the working image:\n"
            "halving the scale quarters every blob, so divide\nmin_area and src_min_area by 4."
        )
        warn.setWordWrap(True)
        return self._page(
            self._button("Open Video…", self.open_dialog),
            self._button("Stop", self.stop),
            self.k_scale,
            warn,
        )

    def _basic_page(self) -> QWidget:
        self.k_bright = Knob("Brightness", -100, 100, 0)
        self.k_contrast = Knob("Contrast", 0.1, 3.0, 1.0, 100)
        self.k_sat = Knob("Saturation", 0.0, 3.0, 1.0, 100)
        self.k_gamma = Knob("Gamma", 0.1, 3.0, 1.0, 100)
        return self._page(self.k_bright, self.k_contrast, self.k_sat, self.k_gamma)

    def _space_page(self) -> QWidget:
        self.c_space = QComboBox()
        self.c_space.addItems(SPACES)
        note = QLabel("HSV and LAB are shown as raw channels, i.e. false colour.")
        note.setWordWrap(True)
        return self._page(self.c_space, note)

    def _contour_page(self) -> QWidget:
        self.x_contours = QCheckBox("Enable contour finding")
        self.k_contour_thresh = Knob("Threshold (0 = Otsu)", 0, 255, 0)
        self.k_contour_area = Knob("Min contour area", 0, 5000, 200)
        self.c_contour_view = QComboBox()
        self.c_contour_view.addItems(CONTOUR_VIEWS)
        note = QLabel(
            "While this is on, the Steam-Tune pipeline only keeps plume pixels that "
            "fall inside these contours — a source venting outside them drops out of "
            "the count entirely."
        )
        note.setWordWrap(True)
        return self._page(
            self.x_contours, self.k_contour_thresh, self.k_contour_area, self.c_contour_view, note
        )

    def _motion_page(self) -> QWidget:
        self.x_bgsub = QCheckBox("Enable background subtraction")
        self.c_bgsub = QComboBox()
        self.c_bgsub.addItems(("MOG2", "KNN"))
        self.c_bgout = QComboBox()
        self.c_bgout.addItems(("Motion Mask", "Background Removed"))
        note = QLabel(
            "MOG2 and KNN assume a fixed camera. On the drone clips they mostly report "
            "the drone; that is why the plume pipeline aligns frames instead."
        )
        note.setWordWrap(True)
        return self._page(
            self.x_bgsub,
            self.c_bgsub,
            self.c_bgout,
            self._button("Reset background model", self.reset_bgsub),
            note,
        )

    def _steam_page(self) -> QWidget:
        """The plume knobs, generated from tune.KNOBS -- one table, two front ends."""
        self.x_steam = QCheckBox("Enable plume pipeline (slow: aligns neighbour frames)")
        self.c_steam_view = QComboBox()
        self.c_steam_view.addItems(STEAM_VIEWS)

        self.knobs: dict[str, Knob] = {}
        groups = [QGroupBox(name.split(" ", 1)[1].title()) for name in PANELS]
        layouts = [QVBoxLayout(group) for group in groups]
        for panel, label, field, hi, scale, doc in KNOBS:
            knob = Knob(label.replace(" x10", ""), 0, hi / scale, getattr(self.cfg, field), scale, doc)
            self.knobs[field] = knob
            layouts[panel].addWidget(knob)

        return self._page(self.x_steam, self.c_steam_view, *groups)

    # --- state -------------------------------------------------------------

    def read_settings(self) -> None:
        """Rebuild both parameter bundles from the widgets and hand them to the worker.

        One method reads every widget, so a new control only has to be created and
        listed here -- there is no per-widget signal wiring to keep in sync.
        """
        self.settings = Settings(
            brightness=int(self.k_bright.value()),
            contrast=self.k_contrast.value(),
            saturation=self.k_sat.value(),
            gamma=self.k_gamma.value(),
            space=self.c_space.currentIndex(),
            contours=self.x_contours.isChecked(),
            contour_thresh=int(self.k_contour_thresh.value()),
            contour_min_area=int(self.k_contour_area.value()),
            contour_view=self.c_contour_view.currentIndex(),
            bgsub=self.x_bgsub.isChecked(),
            bgsub_knn=self.c_bgsub.currentIndex() == 1,
            bgsub_mask_only=self.c_bgout.currentIndex() == 0,
            steam=self.x_steam.isChecked(),
            steam_view=self.c_steam_view.currentIndex(),
            scale=self.k_scale.value(),
        )
        values = {
            field: int(knob.value()) if field in INT_FIELDS else knob.value()
            for field, knob in self.knobs.items()
        }
        for field in ("stride", "window"):
            values[field] = max(1, values[field])  # zero is a crash, not a setting
        self.cfg = Config(**{**asdict(self.cfg), **values})
        if self.worker:
            self.worker.cfg = self.cfg
            self.worker.settings = self.settings

    def write_settings(self, s: Settings) -> None:
        """The inverse of read_settings: put a loaded Settings back into the widgets."""
        for knob, value in (
            (self.k_scale, s.scale),
            (self.k_bright, s.brightness),
            (self.k_contrast, s.contrast),
            (self.k_sat, s.saturation),
            (self.k_gamma, s.gamma),
            (self.k_contour_thresh, s.contour_thresh),
            (self.k_contour_area, s.contour_min_area),
        ):
            knob.set_value(value)
        for combo, index in (
            (self.c_space, s.space),
            (self.c_contour_view, s.contour_view),
            (self.c_bgsub, int(s.bgsub_knn)),
            (self.c_bgout, 0 if s.bgsub_mask_only else 1),
            (self.c_steam_view, s.steam_view),
        ):
            combo.setCurrentIndex(index)
        for check, state in (
            (self.x_contours, s.contours),
            (self.x_bgsub, s.bgsub),
            (self.x_steam, s.steam),
        ):
            check.setChecked(state)

    def _controls(self):
        """Every widget read_settings looks at, so wiring and loading stay in step."""
        knobs = (
            self.k_scale, self.k_bright, self.k_contrast, self.k_sat, self.k_gamma,
            self.k_contour_thresh, self.k_contour_area, *self.knobs.values(),
        )
        combos = (
            self.c_space, self.c_contour_view, self.c_bgsub, self.c_bgout, self.c_steam_view,
        )
        return knobs, combos, (self.x_contours, self.x_bgsub, self.x_steam)

    def connect_widgets(self) -> None:
        """Every control routes to the same read_settings, wired once after construction."""
        knobs, combos, checks = self._controls()
        for knob in knobs:
            knob.slider.valueChanged.connect(self.read_settings)
        for combo in combos:
            combo.currentIndexChanged.connect(self.read_settings)
        for check in checks:
            check.toggled.connect(self.read_settings)

    # --- actions -----------------------------------------------------------

    def open_dialog(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            self, "Open video", "", "Video (*.mp4 *.mov *.avi);;All (*)"
        )
        if path:
            self.start(path)

    def start(self, path: str) -> None:
        self.stop()
        self.read_settings()
        self.worker = VideoWorker(path, self.cfg, self.settings)
        self.worker.frame_ready.connect(self.show_frame)
        self.worker.status.connect(self.statusBar().showMessage)
        self.worker.opened.connect(self.on_opened)
        self.worker.position.connect(self.on_position)
        self.worker.start()
        self.b_play.setText("Pause")

    def stop(self) -> None:
        if self.worker:
            self.worker.stop()
            self.worker = None
        self.seek.setEnabled(False)

    def reset_bgsub(self) -> None:
        if self.worker:
            self.worker.reset_bgsub()

    def show_frame(self, image: QImage) -> None:
        self.video.setPixmap(
            QPixmap.fromImage(image).scaled(
                self.video.size(),
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation,
            )
        )

    def load_session(self) -> None:
        path, _ = QFileDialog.getOpenFileName(self, "Load config", "tune.json", "JSON (*.json)")
        if not path:
            return
        self.cfg, settings = load_session(path)
        for field, knob in self.knobs.items():
            knob.set_value(getattr(self.cfg, field))
        self.write_settings(settings)
        self.read_settings()
        self.statusBar().showMessage(f"loaded {path}")

    def save_session(self) -> None:
        path, _ = QFileDialog.getSaveFileName(self, "Save config", "tune.json", "JSON (*.json)")
        if path:
            self.read_settings()
            save_session(self.cfg, self.settings, path)
            self.statusBar().showMessage(f"saved {path}")

    def closeEvent(self, event) -> None:
        self.stop()
        super().closeEvent(event)


def save_session(cfg: Config, settings: Settings, path: str) -> None:
    """Every knob in the window, written to the file `steam-detect --config` reads.

    The view settings go in under "view", which `build_config` drops on the way back
    out because it keeps only Config's own fields. So one file carries both halves,
    `steam-detect` and `steam-tune` ignore the half they do not understand, and there
    is no second format to keep in sync.
    """
    Path(path).write_text(json.dumps(asdict(cfg) | {"view": asdict(settings)}, indent=2) + "\n")


def load_session(path: str) -> tuple[Config, Settings]:
    """(Config, Settings) from one file. A tune.json without a "view" gives defaults."""
    known = {f.name for f in fields(Settings)}
    view = json.loads(Path(path).read_text()).get("view", {})
    return build_config(path), Settings(**{k: v for k, v in view.items() if k in known})


def with_signals_off(widget, action) -> None:
    """Change a widget from code without it reporting the change back as user input."""
    widget.blockSignals(True)
    action()
    widget.blockSignals(False)


def main() -> None:
    app = QApplication(sys.argv)
    window = MainWindow(build_config())
    window.connect_widgets()
    window.resize(1280, 760)
    window.show()
    if len(sys.argv) > 1:  # ponytail: a path argument, not a CLI -- the dialog is the UI
        window.start(sys.argv[1])
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
